version: 2.1

orbs:
  gh: circleci/github-cli@2.1.1

jobs:
  auth:
    docker:
      - image: cimg/base:stable
    environment:
      GITHUB_USER: kelvintaywl
    steps:
      - gh/setup
      - checkout
      - run:
          name: push new branch
          command: |
            git config --global user.email "dummy@local"
            git config --global user.name "${GITHUB_USER}"
            BRANCH="foobar_${CIRCLE_SHA1:0:7}"
            git checkout -b $BRANCH
            git commit --allow-empty -m "[skip ci] dummy"
            git push -u origin $BRANCH

workflows:
  gh:
    jobs:
      - auth
