version: 2.1

orbs:
  gh: circleci/github-cli@2.1.1

jobs:
  auth:
    docker:
      - image: cimg/base:stable
    environment:
      GITHUB_USER: kelvintaywl
    steps:
      - gh/setup
      - checkout
      - run:
          name: push new branch
          command: |
            git config --global user.email "dummy@local"
            git config --global user.name "${GITHUB_USER}"

            # switch to git+https, not git+ssh
            git config --global url."https://github.com/".insteadOf git@github.com:
            git config --global url."https://".insteadOf git://

            # update remote URL, and add our GITHUB_TOKEN for auth
            git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git"
            
            BRANCH="foobar_${CIRCLE_SHA1:0:7}"
            git checkout -b $BRANCH
            git commit --allow-empty -m "[skip ci] dummy"
            git push -u origin $BRANCH

workflows:
  gh:
    jobs:
      - auth
